### ISSUE TITLE
wiki migration

### ISSUE THREAD

**Issue by rvosa** [nexml/nexml#1]
Move the wiki from sourceforge (http://sourceforge.net/apps/mediawiki/nexml/index.php?title=Manual) to somewhere else, e.g. here on github

**Comment by hlapp** [comment]
It looks like the content migration has happened meanwhile. At least http://nexml.org/manual redirects to the Github wiki. If indeed the Github wiki is now the authoritative manual, the [wiki at the Sf.net repo](https://sourceforge.net/apps/mediawiki/nexml/index.php?title=Main_Page) should be updated accordingly - the manual seems to be the only content there, yet there's no indication that it is stale and outdated.

I don't have editing privileges there, otherwise I'd just do it myself.

**Comment by rvosa** [comment]
Updated, the SF wiki is now gone and a note that github is now the home has been added.
